\thispagestyle{empty}
% zentriert: 0.26cm
\hoffset=0.4cm
\begin{center}
\begin{figure}
\centering
\includegraphics[width=10cm]{thesis/img/uniol_4c}\\
\end{figure}
\vspace{2cm}
% TODO: Department pruefen/anpassen (Vorlage stammt aus der Informatik)
{\bf Department f\"ur Wirtschafts- und Rechtswissenschaften}\\[0.1cm]
% [ggf. Abteilung erg\"anzen]
\vspace{4cm}
{\bf Masterarbeit}\\
\vspace{.5cm}
{\begin{minipage}[t]{12cm}
\centering
\Large
Demand Estimation with Unstructured Product Data
\end{minipage}}\\
\vspace{3cm}
Burak Uzun\\
\vspace{.5cm}
10.08.2026\\
\vspace{3cm}
1. Gutachter: Prof. Dr. Cristian Huse\\
2. Gutachter: Thomas Handke
\end{center}
\newpage
